# Generated by Django 4.2.10 on 2025-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('adminuser', 'AdminUser'), ('regularuser', 'Regularuser')], default=None, max_length=20, null=True),
        ),
    ]
